---
# tasks file for nginx
#
- name: Ensure nginx directory on docker host
  file:
    state: directory
    recurse: yes
    owner: 1000
    group: 1000
    path: 
    - /data/nginx/logs
    - /data/nginx/conf/jenkins.conf

- name: copy jenkins.conf into data dir
  template:
    src: jenkins.conf.j2
    dest: /data/nginx/conf/jenkins.conf

- name: Pull the latest official nginx docker image
  docker_image:
    name: "nginx"

- name: Create a container from the nginx docker image
  docker_container:
    name: "nginx-server"
    image: "nginx"
    ports:
        - "80:80"
    volumes:
        - "/data/nginx/conf/jenkins.conf:/etc/nginx/conf.d/default.conf"
        - "/data/nginx/logs:/var/log/nginx"
    state: started
    recreate: no

