---
- name: Ansible deployments
  become: yes
  hosts: local
  gather_facts: true

  roles:
    - { role: apache, tags: apache-install }
    - { role: docker, tags: docker-install }
    - { role: jenkins, tags: jenkins-install }
    - { role: nginx, tags: nginx-install }
